# SITE SETUP
# Guide: https://wowchemy.com/docs/getting-started/
# Documentation: https://wowchemy.com/docs/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance

appearance:
  # theme_day: Mr Robot
  theme_night: Mr Robot
  font: minimal
  font_size: M

# SEO

marketing:
  seo:
    site_type: ResearchOrganization
    local_business_type: ''
    org_name: 'Ackels lab'
    description: 'Sensory dynamics and behavior laboratory'
    twitter: 'tobiasackels'
  analytics:
    google_analytics: 'Ackels lab'
    baidu_tongji: ''
  verification:
    google: 'google-site-verification=m4O1-gklU8VtvheWbOgWamq_GQbx55p8QQB0tHQ9G3g'
    baidu: ''

# Site header

header:
  navbar:
    enable: true
    align: r
    show_logo: true
    show_language: false
    show_day_night: false
    show_search: false
    highlight_active_link: true

# Site footer

footer:
  copyright:
    # notice: '© {year} Tobias Ackels. This work is licensed under {license}'
    notice: '© {year} by Tobias Ackels.'
    license:
      enable: false
      allow_derivatives: false
      share_alike: false
      allow_commercial: false

# Localization

locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'
  address_format: en-us

# Site features

features:
  syntax_highlighter:
    enable: false
    extra_languages:
      - r
      - latex
  math:
    enable: false
  privacy_pack:
    enable: false
  repository:
    url: 'https://github.com/tobiasackels/ackels-lab'
    content_dir: content
    branch: preview
  avatar:
    gravatar: false
    shape: circle
  comment:
    provider: ''
    disqus:
      shortname: ''
      show_count: true
    commento:
      url: ''
    giscus:
      repo: ''
      repo_id: ''
      category: ''
      category_id: ''
  search:
    provider: wowchemy
    algolia:
      app_id: ''
      api_key: ''
      index_name: ''
      show_logo: false
  map:
    provider: 'mapnik'
    api_key: ''
    zoom: 16

# Extensions

extensions:
  cms:
    branch: main
    local_backend: false
  academicons:
    enable: true

# Citation style

publications:
  date_format: January 2006
  citation_style: mla
